export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const REQUEST_CURRENT_USER = 'REQUEST_CURRENT_USER';
export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER';
export const NO_TOKEN = 'NO_TOKEN';
