// UI
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const TOGGLE_RIGHT_SIDEBAR = 'TOGGLE_RIGHT_SIDEBAR';
export const TOGGLE_NEW_ITEM_MODAL = 'TOGGLE_NEW_ITEM_MODAL';
export const TOGGLE_SAMPLE_SELECT = 'TOGGLE_SAMPLE_SELECT';
export const TOGGLE_ALL_SAMPLES_SELECT = 'TOGGLE_ALL_SAMPLES_SELECT';
export const SET_SAMPLE_SEARCH = 'SET_SAMPLE_SEARCH';
export const REORDER_SAMPLES = 'REORDER_SAMPLES';
// Auth
export const REQUEST_CURRENT_USER = 'REQUEST_CURRENT_USER';
export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER';
export const NO_TOKEN = 'NO_TOKEN';
// Fetches
export const RECEIVE_ADDED_SAMPLE = 'RECEIVE_ADDED_SAMPLE';
export const RECEIVE_DELETED_SAMPLES = 'RECEIVE_DELETED_SAMPLES';

export const RECEIVE_ADDED_LIBRARY = 'RECEIVE_ADDED_LIBRARY';
export const RECEIVE_EDITED_LIBRARY = 'RECEIVE_EDITED_LIBRARY';
export const RECEIVE_DELETED_LIBRARY = 'RECEIVE_DELETED_LIBRARY';

export const RECEIVE_ADDED_FOLDER = 'RECEIVE_ADDED_FOLDER';
export const RECEIVE_EDITED_FOLDER = 'RECEIVE_EDITED_FOLDER';
export const RECEIVE_DELETED_FOLDER = 'RECEIVE_DELETED_FOLDER';
