// UI
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const TOGGLE_RIGHT_SIDEBAR = 'TOGGLE_RIGHT_SIDEBAR';
export const TOGGLE_NEW_ITEM_MODAL = 'TOGGLE_NEW_ITEM_MODAL';
export const TOGGLE_SAMPLE_SELECT = 'TOGGLE_SAMPLE_SELECT';
export const TOGGLE_ALL_SAMPLES_SELECT = 'TOGGLE_ALL_SAMPLES_SELECT';
export const REORDER_SAMPLES = 'REORDER_SAMPLES';
// filtering
export const SET_SAMPLE_SEARCH = 'SET_SAMPLE_SEARCH';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const CHANGE_TAGS = 'CHANGE_TAGS';
export const CHANGE_SAMPLE_TYPE = 'CHANGE_SAMPLE_TYPE';
export const CHANGE_INSTRUMENT = 'CHANGE_INSTRUMENT';
export const CHANGE_TEMPO = 'CHANGE_TEMPO';
export const CHANGE_KEY = 'CHANGE_KEY';
export const CHANGE_GENRE = 'CHANGE_GENRE';
export const CHANGE_RATING = 'CHANGE_RATING';
export const RESET_FILTERS = 'RESET_FILTERS';
// Auth
export const REQUEST_CURRENT_USER = 'REQUEST_CURRENT_USER';
export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER';
export const NO_TOKEN = 'NO_TOKEN';
// Fetches
// samples
export const RECEIVE_ADDED_SAMPLE = 'RECEIVE_ADDED_SAMPLE';
export const RECEIVE_EDITED_SAMPLES = 'RECEIVE_EDITED_SAMPLES';
export const RECEIVE_DELETED_SAMPLES = 'RECEIVE_DELETED_SAMPLES';
// libraries
export const RECEIVE_ADDED_LIBRARY = 'RECEIVE_ADDED_LIBRARY';
export const RECEIVE_EDITED_LIBRARY = 'RECEIVE_EDITED_LIBRARY';
export const RECEIVE_DELETED_LIBRARY = 'RECEIVE_DELETED_LIBRARY';
// folders
export const RECEIVE_ADDED_FOLDER = 'RECEIVE_ADDED_FOLDER';
export const RECEIVE_EDITED_FOLDER = 'RECEIVE_EDITED_FOLDER';
export const RECEIVE_DELETED_FOLDER = 'RECEIVE_DELETED_FOLDER';
// tags
export const RECEIVE_ADDED_TAG = 'RECEIVE_ADDED_TAG';
export const RECEIVE_EDITED_TAG = 'RECEIVE_EDITED_TAG';
export const RECEIVE_DELETED_TAG = 'RECEIVE_DELETED_TAG';
export const UPDATE_TAG_COUNT = 'UPDATE_TAG_COUNT';
